#+TITLE: A minimal ActivityPub server

A minimal ActivityPub server intended for demonstrating use-cases of ActivityPub and experimenting with ideas.

* Starting it

Prerequisites:

- [[https://www.gnu.org/software/guile/][GNU Guile]]
- [[https://github.com/aconchillo/guile-json][guile-json]]

#+BEGIN_SRC sh
./bootstrap
./configure
./pre-inst-env guile main.scm
#+END_SRC

* Quick tour
** Actor

Actor objects can be retrieved with a GET request to the ~/actors/actor-name~ endpoint.

For example we can retrieve the actor object for Alice:

#+BEGIN_SRC restclient
GET http://localhost:8080/actors/alice
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "http://localhost:8080/actors/alice",
  "name": "Alice",
  "type": "Person",
  "inbox": "http://localhost:8080/actors/alice/inbox",
  "outbox": "http://localhost:8080/actors/alice/outbox"
}
// GET http://localhost:8080/actors/alice
// HTTP/1.1 200 OK
// Content-Length: 229
// Content-Type: application/json;charset=utf-8
// Access-Control-Allow-Origin: *
// Request duration: 0.001744s
#+END_SRC

*** Inbox
We can retrieve Alice's inbox (which is currently empty):

#+BEGIN_SRC restclient
GET http://localhost:8080/actors/alice/inbox
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Collection",
  "totalItems": 0,
  "items": []
}
// GET http://localhost:8080/actors/alice/inbox
// HTTP/1.1 200 OK
// Content-Length: 98
// Content-Type: application/json;charset=utf-8
// Access-Control-Allow-Origin: *
// Request duration: 0.001924s
#+END_SRC

*** Outbox

We can also retrieve Alice's outbox (also still empty):

#+BEGIN_SRC restclient
GET http://localhost:8080/actors/alice/outbox
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Collection",
  "totalItems": 0,
  "items": []
}
// GET http://localhost:8080/actors/alice/outbox
// HTTP/1.1 200 OK
// Content-Length: 98
// Content-Type: application/json;charset=utf-8
// Access-Control-Allow-Origin: *
// Request duration: 0.002938s
#+END_SRC
** Posting an activity
Alice can post a note by making a ~POST~ request to her outbox.

For example she can post a very simple note (addressed to Bob):
#+BEGIN_SRC restclient
POST http://localhost:8080/actors/alice/outbox
Content-type: application/json
{
  "type": "Create",
  "to": [ "http://localhost:8080/actors/bob", "http://localhost:8080/actors/alice" ],
  "object": {
    "content": "Hello World!",
    "type": "Note"
  }
}
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "http://localhost:8080/objects/1",
  "type": "Create",
  "actor": "http://localhost:8080/actors/alice",
  "object": {
    "type": "Note",
    "content": "Hello World!"
  },
  "to": [
    "http://localhost:8080/actors/bob",
    "http://localhost:8080/actors/alice"
  ]
}
// POST http://localhost:8080/actors/alice/outbox
// HTTP/1.1 200 OK
// Content-Length: 281
// Content-Type: application/json;charset=utf-8
// Access-Control-Allow-Origin: *
// Request duration: 0.001252s
#+END_SRC

Note that the note was wrapped in a create activity and attributed to Alice.

The activity is now placed in Alice's outbox:

#+BEGIN_SRC restclient
GET http://localhost:8080/actors/alice/outbox
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Collection",
  "totalItems": 1,
  "items": [
    {
      "id": "http://localhost:8080/objects/1",
      "type": "Create",
      "actor": "http://localhost:8080/actors/alice",
      "object": {
        "type": "Note",
        "content": "Hello World!"
      },
      "to": [
        "http://localhost:8080/actors/bob",
        "http://localhost:8080/actors/alice"
      ]
    }
  ]
}
// GET http://localhost:8080/actors/alice/outbox
// HTTP/1.1 200 OK
// Content-Length: 328
// Content-Type: application/json;charset=utf-8
// Access-Control-Allow-Origin: *
// Request duration: 0.001692s
#+END_SRC

And in Bob's inbox:

#+BEGIN_SRC restclient
GET http://localhost:8080/actors/bob/inbox
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Collection",
  "totalItems": 1,
  "items": [
    {
      "id": "http://localhost:8080/objects/1",
      "type": "Create",
      "actor": "http://localhost:8080/actors/alice",
      "object": {
        "type": "Note",
        "content": "Hello World!"
      },
      "to": [
        "http://localhost:8080/actors/bob",
        "http://localhost:8080/actors/alice"
      ]
    }
  ]
}
// GET http://localhost:8080/actors/bob/inbox
// HTTP/1.1 200 OK
// Content-Length: 328
// Content-Type: application/json;charset=utf-8
// Access-Control-Allow-Origin: *
// Request duration: 0.001684s
#+END_SRC
